# Feel free to disable non-critical HA parts during devel by commenting out
# Generated in hadk by executing: cd $ANDROID_ROOT; rpm/helpers/add_new_device.sh

Description: Pattern with packages for find5 configurations
Name: jolla-configuration-find5
Requires:
- pattern:jolla-hw-adaptation-find5
- pattern:jolla-configuration-sfe

Summary: Jolla Configuration find5

